import {
  HomeIcon,
  InformationCircleIcon,
  PhoneIcon,
  RocketLaunchIcon,
  ArrowLeftOnRectangleIcon,
  ArrowRightOnRectangleIcon,
  UserPlusIcon,
  UserIcon,
  CommandLineIcon,
  IdentificationIcon,
  UsersIcon,
  QuestionMarkCircleIcon,
  PaperClipIcon,
  Cog6ToothIcon,
  PlusCircleIcon,
  ListBulletIcon,
  TrophyIcon,
  ChatBubbleLeftRightIcon,
  HashtagIcon,
  PuzzlePieceIcon,
  VideoCameraIcon,
  BookmarkSquareIcon,
  PlayCircleIcon,
  ChatBubbleLeftIcon,
  LightBulbIcon,
  ChatBubbleOvalLeftEllipsisIcon,
} from '@heroicons/react/24/outline';
import { TRoutes } from '@/types';

export const routes: TRoutes = [
  {
    path: '/',
    component: 'Home',
    exact: false,
    name: 'Bosh sahifa',
    Icon: HomeIcon,
    home: true,
    submenus: [],
  },
  {
    path: '/courses',
    component: 'Courses',
    exact: false,
    name: 'Kurslar',
    Icon: PlayCircleIcon,
    home: false,
    submenus: [],
  },
  {
    path: '/forum',
    component: 'Forum',
    exact: false,
    name: 'Forum',
    Icon: ChatBubbleLeftRightIcon,
    home: false,
    submenus: [
      {
        path: '',
        component: 'Questions',
        exact: false,
        name: 'Savollar',
        childPath: '/question',
        Icon: PuzzlePieceIcon,
      },
      // {
      //   path: "/tags",
      //   component: "Tags",
      //   exact: false,
      //   name: "Taglar",
      //   Icon: HashtagIcon,
      // },
      {
        path: '/create',
        component: 'Create',
        exact: false,
        name: 'Savol yaratish',
        Icon: PlusCircleIcon,
      },
    ],
  },
  {
    path: '/blog',
    component: 'Blog',
    exact: false,
    name: 'Maqolalar',
    Icon: BookmarkSquareIcon,
    home: false,
    submenus: [
      {
        path: '',
        component: 'Blog',
        exact: false,
        name: 'Maqolalar',
        childPath: '/post',
        Icon: ListBulletIcon,
      },
      {
        path: '/create',
        component: 'Create',
        exact: false,
        name: 'Maqola yaratish',
        Icon: PlusCircleIcon,
      },
    ],
  },
  // {
  // 	path: "/contact",
  // 	component: "Contact",
  // 	exact: false,
  // 	name: "Aloqa",
  // 	Icon: PhoneIcon,
  // 	home: false,
  // 	submenus: [],
  // },
  {
    path: '/dg-contest',
    component: 'Contests',
    exact: false,
    name: 'DG Kontest',
    Icon: LightBulbIcon,
    home: false,
    submenus: [
      {
        path: '/contests',
        component: 'Contests',
        exact: false,
        name: 'Tanlovlar',
        // childPath: '/contest',
        Icon: TrophyIcon,
      },
      {
        path: '/problemsets',
        component: 'Problemsets',
        exact: false,
        name: 'Mashqlar',
        Icon: CommandLineIcon,
      },
      {
        path: '/users',
        component: 'Users',
        exact: false,
        name: 'Foydalanuvchilar',
        Icon: UsersIcon,
      },
      // {
      // 	path: "/contest",
      // 	component: "Contest",
      // 	exact: false,
      // 	name: "Ro`yxat",
      // 	Icon: ListBulletIcon,
      // },
      // {
      // 	path: "/contest/participants",
      // 	component: "Participants",
      // 	exact: false,
      // 	name: "Qatnashuvchilar",
      // 	Icon: UserGroupIcon,
      // },
      // {
      // 	path: "/contest/tries",
      // 	component: "Tries",
      // 	exact: false,
      // 	name: "Urinishlar",
      // 	Icon: BoltIcon,
      // },
      // {
      // 	path: "/contest/problems",
      // 	component: "Problems",
      // 	exact: false,
      // 	name: "Masalalar",
      // 	Icon: Cog6ToothIcon,
      // },
    ],
  },
  // {
  //   path: "/signup",
  //   component: "Sign up",
  //   exact: true,
  //   name: "Ro'yxatdan o'tish",
  //   Icon: UserPlusIcon,
  //   home: false,
  //   submenus: [],
  // },
  // {
  //   path: "/signin",
  //   component: "Sign in",
  //   exact: false,
  //   name: "Kirish",
  //   Icon: ArrowLeftOnRectangleIcon,
  //   home: false,
  //   submenus: [],
  // },
  // {
  //   path: "/profile",
  //   component: "Profile",
  //   exact: true,
  //   name: "Profil",
  //   Icon: UserIcon,
  //   home: false,
  //   submenus: [
  //     {
  //       path: "/",
  //       component: "Profile",
  //       exact: false,
  //       name: "Mening hisobim",
  //       Icon: IdentificationIcon,
  //     },
  //     // {
  //     //   path: "/update",
  //     //   component: "Update",
  //     //   exact: false,
  //     //   name: "O`zgartirish",
  //     //   Icon: Cog6ToothIcon,
  //     // },
  //     {
  //       path: "/signout",
  //       name: "Chiqish",
  //       component: "Sign out",
  //       exact: false,
  //       Icon: ArrowRightOnRectangleIcon,
  //     },
  //   ],
  // },
];

export const features = [
  {
    path: '/settings',
    name: 'Sozlamalar',
    description: 'Sozlamalar',
    Icon: Cog6ToothIcon,
  },
  {
    path: '/feedback',
    name: 'Mulohaza yuborish',
    description: 'Mulohaza',
    Icon: ChatBubbleOvalLeftEllipsisIcon,
  },
];
